name: Update the cache

permissions:
  contents: write

on:
  schedule:
    # build monday mornings.
    - cron:  '0 2 * * 1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install icalendar

      - name: Build
        run: |
          rm -f basic.ics
          wget https://calendar.google.com/calendar/ical/5l6o0msfduoir59hrab0jlkocc%40group.calendar.google.com/public/basic.ics -O basic.ics
          python export.py

      - name: Commit
        run: |
            git config --global user.email "bot@hexylena.github.io"
            git config --global user.name "Github Actions Bot"
            git add *.ics
            git commit -a -m 'Automated commit'
            git push
        continue-on-error: true
